coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        if_no_uploads: error

    patch: false

    changes: true

comment:
  layout: "header, diff, changes, suggestions"
  behavior: default
