language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_FILE=cmake-3.5.2-Linux-x86_64.tar.gz
    - CMAKE_URL=http://www.cmake.org/files/v3.5/${CMAKE_FILE}
    - CMAKE_BUILD_TYPE=Release

matrix:
  include:
    - compiler: gcc
      env: GCC_VER=5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
        packages:
          - g++-5
          - gcc-5
    - compiler: gcc
      env: GCC_VER=6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - gcc-6
    - compiler: clang
      env: GLANG_VER=3.6
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
        packages:
          - clang-3.6
    - compiler: clang
      env: GLANG_VER=3.7
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.7
        packages:
          - clang-3.7

before_install:
  - |
    if [ "${CXX}" = "g++" ]
        then export CXX="g++-${GCC_VER}" CC="gcc-${GCC_VER}"
    fi
  - |
    if [ "${CXX}" = "clang++" ]
        then export CXX="clang++-${CLANG_VER}" CC="clang-${CLANG_VER}"
    fi
  - mkdir -p ${DEPS_DIR}

install:
  - wget ${CMAKE_URL} --quiet --no-check-certificate
  - mkdir -p cmake
  - tar -xzf ${CMAKE_FILE} -C cmake --strip-components 1
  - mv cmake ${DEPS_DIR}
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

script:
  - cmake . && make all
  - ./bin/unittests
