language: cpp

matrix:
  include:
    - compiler: gcc
      env: GCC_VER=5
    - compiler: gcc
      env: GCC_VER=6
    - compiler: clang
      env: CLANG_VER=3.6
    - compiler: clang
      env: CLANG_VER=3.7

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - clang-3.7
      - g++-5
      - gcc-5
      - g++-6
      - gcc-6

before_install:
  - |
    if [ "${CXX}" = "g++" ]
        then export CXX="g++-${GCC_VER}" CC="gcc-${GCC_VER}"
    fi
  - |
    if [ "${CXX}" = "clang++" ]
        then export CXX="clang++-${CLANG_VER}" CC="clang-${CLANG_VER}"
    fi
  - mkdir -p ${DEPS_DIR}

install:
  - wget ${CMAKE_URL} --quiet --no-check-certificate
  - mkdir -p cmake
  - tar -xzf ${CMAKE_FILE} -C cmake --strip-components 1
  - mv cmake ${DEPS_DIR}
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

script:
  - cmake . && make all
  - ./bin/unittests
