language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_FILE=cmake-3.5.2-Linux-x86_64.tar.gz
    - CMAKE_URL=http://www.cmake.org/files/v3.5/${CMAKE_FILE}

compiler:
  - gcc
  - clang

before_install:
  - mkdir -p ${DEPS_DIR}

install:
  - wget ${CMAKE_URL} --quiet --no-check-certificate
  - mkdir -p cmake
  - tar -xzf ${CMAKE_FILE} -C cmake --strip-components 1
  - mv cmake ${DEPS_DIR}
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release
