language: cpp

env:
  matrix:
    - GCC_VER=5 CLANG_VER=3.6
    - GCC_VER=6 CLANG_VER=3.7
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_FILE=cmake-3.5.2-Linux-x86_64.tar.gz
    - CMAKE_URL=http://www.cmake.org/files/v3.5/${CMAKE_FILE}
    - CMAKE_BUILD_TYPE=Release

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-${CLANG_VER}
      - g++-${GCC_VER}
      - gcc-${GCC_VER}

before_install:
  - |
    if [ "${CXX}" = "g++" ]
        then export CXX="g++-${GCC_VER}" CC="gcc-${GCC_VER}"
    fi
  - |
    if [ "${CXX}" = "clang++" ]
        then export CXX="clang++-${CLANG_VER}" CC="clang-${CLANG_VER}"
    fi
  - mkdir -p ${DEPS_DIR}

install:
  - wget ${CMAKE_URL} --quiet --no-check-certificate
  - mkdir -p cmake
  - tar -xzf ${CMAKE_FILE} -C cmake --strip-components 1
  - mv cmake ${DEPS_DIR}
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

script:
  - cmake . && make all
  - ./bin/unittests -r compact
